language: go

go:
  - "1.7"
  - "1.8"
  - "1.9"
  - "1.10.x"
  - "tip"

env:
  - "PATH=/home/travis/gopath/bin:$PATH"

install:
  - go get -v -t .

script:
  - go get -u github.com/golang/lint/golint
  - golint ./... | grep -v vendor/
  - make
  - scripts/check-code-generation-ran.sh
  # run integration tests
  - make testacc

matrix:
    allow_failures:
        - go: tip
